#! /bin/sh
ln -sf driver/*.F* .
ln -sf state/dynvars_h/*.F* .
ln -sf state/export/*.F* .
ln -sf state/ffields_h/*.F* .
ln -sf state/import/*.F* .
ln -sf state/mitgcm_state/*.F* .
ln -sf state/stackvars/*.F* .
ln -sf state/timevars/*.F* .
ln -sf utils/*.F* .
