#!/bin/bash
# Instructions and script for connecting to engaging by vnc
# Greg suggests that X2Go might be a better option, lighter on resources.

# 1. Request account on engaging at  https://eofe1.mit.edu/request_account

# 2. Log in to eofe4 or eofe5 and start vncserver
#    ssh -l UserName eofe(4/5).mit.edu
#    vncserver -localhost -geometry 1600x1200
#       # For geometry pick your favorite screen size,
#       # best if it's <= screen resolution of local display.
#       # First time you start it will ask you te create a VNC password.
#       # Take note of screen in line: "New 'eofe5:3 ..."
#       # In above case it's screen 3 on eofe5
#    exit

# 3. Install vnc client on local machine
#    The Mac comes with "Screen Sharing" client, but it's slow.
#    A better client is: https://sourceforge.net/projects/turbovnc/
#    On 'buntu I like package ssvcn

# 4. Start vnc client on local machine
#    These lines automate start-up of vnc client, assuming
#    you are using OS X El Capitan with TurboVNC or 'buntu with ssvnc.
#    But you can comment and start manually, or replace your
#    own favorite client here.
if [[ "$OSTYPE" == 'darwin15' ]]
then
    open /Applications/Utilities/TurboVNC/TurboVNC\ Viewer.app
else
     ssvnc eofe &
fi

# 5. Establish ssh tunnel
#    The line below assumes that you are commecting to eofe5:3
#    but you can change this to eof4 ------------------v
xterm -e ssh -x -t -L 5901:127.0.0.1:5903 dmenemen@eofe5.mit.edu &
#    and this to assigned X desktop ---^^
#    Also the "xterm -e" part can be removed.

# 6. Establish connection on local vnc client from step 4.
#    For Mac turboVNC:
#        VNC server: localhost:5901
#        Press "Connect"
#        Password: Your_VNC_password_from_step_2
#    For 'buntu ssvnc
#        VNC Host:Display localhost:5901
#        VNC Password Your_VNC_password_from_step_2
#        Use SSL/SSH: None

# 7. IMPORTANT: Disable ScreenSaver
#    System/Preferences/Screensaver
#    Uncheck "Activate screensaver when computer is idle"

# 8. If you ever want to kill your vncserver session
#    vncserver -kill :DesktopScreenNumber

# 9. If eofe4 or eofe5 is rebooted while you had active session
#    please remove /tmp/.X11-unix/XN or /tmp/.X0N-lock
#    where N is DesktopScreenNumber, e.g., "3"
#    if you were assigned "New 'eofe5:3 ..." by vncserver.
