/*
 This file created by convert_cpp_cmd2defines with the following command
 line arguments:
 Warning - this file is automatically generated - do NOT edit -bAD_CONFIG_H -UALLOW_ADJOINT_RUN -UALLOW_TANGENTLINEAR_RUN -UALLOW_ECCO_OPTIMIZATION
*/

/*  Warning  */
/*  -  */
/*  this  */
/*  file  */
/*  is  */
/*  automatically  */
/*  generated  */
/*  -  */
/*  do  */
/*  NOT  */
/*  edit  */
#ifndef AD_CONFIG_H
#define AD_CONFIG_H
#undef  ALLOW_ADJOINT_RUN
#undef  ALLOW_TANGENTLINEAR_RUN
#undef  ALLOW_ECCO_OPTIMIZATION
#endif /* AD_CONFIG_H */
